[package]
name = "repro-threshold"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
clap_complete = "4.5.60"
crossterm = { version = "0.29.0", features = ["event-stream"] }
dirs = "6.0.0"
env_logger = "0.11.8"
futures = "0.3.31"
in-toto = "0.4.0"
log = "0.4.28"
pem = "3.0.6"
ratatui = "0.30.0-beta.0"
reqwest = { version = "0.12.24", default-features = false, features = ["rustls-tls-native-roots"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
tokio = { version = "1.48.0", features = ["fs", "macros", "rt-multi-thread"] }
toml = "0.9.8"

[dev-dependencies]
data-encoding = "2.9.0"
